spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true